# Test Analysis
This notebook is for analysing the test data.

Rafa, vc adicionar aqui, eu sou mt ruim de fazer descrição de notebook


In [ ]:
# Standard library imports
import sys
import os

# Third-party imports
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mlp
import seaborn as sns
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, ConcatDataset

# Setting the custom classes
current_dir = os.getcwd() 
utils_path = os.path.abspath(os.path.join(current_dir, '..', '..', 'src', 'utils'))
models_path = os.path.abspath(os.path.join(current_dir, '..', '..', 'src', 'models'))
sys.path.append(utils_path)
sys.path.append(models_path)

print(f"Adicionado ao PATH: {utils_path}")
print(f"Adicionado ao PATH: {models_path}")

# Local/Project imports
import DatasetsDict as dd
import ModelTester as mt
from StaticMaskTraining import StaticMaskTraining
from NotebookUtils import animate_notebook, load_checkpoints

Adicionado ao PATH: /home/andre-marques/Desktop/Estudo/PowerRangersCode/src/utils
Adicionado ao PATH: /home/andre-marques/Desktop/Estudo/PowerRangersCode/src/models


In [6]:
#cuda 
torch.set_default_device('cuda')

In [3]:
# 1. Configurações Iniciais
training_id = "lenet_mnist_01"
epoch_alvo = 15  # O .pt que você quer testar
model_pth = f"{training_id}/checkpoint_epoch_{epoch_alvo}.pt"

# Instanciar o Tester (ajuste o device se necessário)
tester = mt.ModelTester("mnist")

# 2. Executar o Teste
# Note: o seu ModelTester precisa retornar (cm, all_targets, all_probs)
# Se o seu atual só retorna a CM, ajuste o return dele!

cm, all_targets, all_probs, all_predictions = tester.test(
    model_pth="lenet_mnist_01/checkpoint_epoch_115.pt"
)

print(cm)

[[ 970    0    3    1    0    1    1    1    3    0]
 [   0 1128    0    1    0    0    1    2    3    0]
 [   1    0 1024    2    1    0    0    4    0    0]
 [   0    0    3  995    0    7    0    2    2    1]
 [   0    1    2    0  963    0    3    0    1   12]
 [   2    0    0    8    0  878    2    1    1    0]
 [   2    1    2    0    2    7  940    0    4    0]
 [   0    3    4    0    0    0    0 1018    1    2]
 [   0    0    5    6    1    2    0    1  956    3]
 [   1    2    1    1    2    5    0    5    7  985]]
